<body>

    <div class="container-fluid mt-5 text-center">
        <h1>Listar Tabela</h1>
        <hr>
        <table class="table text-center">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Matricula</th>
                    <th>Cidade</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody class="table-secondary table-stripped table-hover">
                <?php
                    foreach ($dados[0] as $cadaAluno) {
                        $id = $cadaAluno['idalunos'];
                        echo "
                        <tr>
                            <td class='pt-3 fw-bold'>{$cadaAluno['idalunos']}</td>
                            <td class='pt-3'>{$cadaAluno['nome']}</td>
                            <td class='pt-3'>{$cadaAluno['matricula']}</td>
                            <td class='pt-3'>{$cadaAluno['cidade']}</td>
                            <td>
                                <a href='/listar?id={$id}'  class='btn btn-warning me-2' >Editar</a>
                                <button onclick='confirmar({$id})' class='btn btn-danger text-white'>Excluir</a>
                            </td>
                        </tr>";
                    }
                ?>
                <!-- data-bs-toggle='modal' data-bs-target='#editModal' -->
            </tbody>
        </table>
    </div>
    <div class="modal fade show" id="editModal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Atualizar informações do aluno:</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="fechar()"></button>
                </div>
                <form action="" method="POST">
                    <div class="modal-body">
                        <label for="nome">Editar nome: </label>
                        <input class="form-control bg-light mb-2" name="valor_nome" id="nome" type="text" value="<?php echo isset($dados[1]["nome"]) ? $dados[1]["nome"] : "";?>">
                        <label for="matricula">Editar matricula: </label>
                        <input class="form-control bg-light mb-2" name="valor_matricula" id="matricula" type="text" value="<?php echo isset($dados[1]["matricula"]) ? $dados[1]["matricula"] : "";?>">
                        <label for="cidade">Editar cidade: </label>
                        <input class="form-control bg-light" name="valor_cidade" id="cidade" type="text" value="<?php echo isset($dados[1]["cidade"]) ? $dados[1]["cidade"] : "";?>">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="fechar()">Cancelar</button>
                        <button name="submeter" class="btn btn-primary">Salvar alterações</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function confirmar(id){
            if(confirm('Tem certeza?')){
                location.href = `/excluir?id=${id}`
            }
        }
    </script>
</body>