<body>

    <div class="container-fluid w-100 mt-5 text-center">
        <h1>Listar Tabela</h1>
        <hr>
        <div class="table-responsive">
            <table class="table table-striped table-hover text-center align-middle">
                <thead class="table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Matricula</th>
                        <th>Cidade</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody class="table-secondary">
                    <?php
                        foreach ($dados[0] as $cadaAluno) {
                            $id = $cadaAluno['idalunos'];
                            echo "
                            <tr>
                                <td class='fw-bold'>{$cadaAluno['idalunos']}</td>
                                <td>{$cadaAluno['nome']}</td>
                                <td>{$cadaAluno['matricula']}</td>
                                <td>{$cadaAluno['cidade']}</td>
                                <td>
                                    <a href='/listar?id={$id}' class='me-2' ><img src='./assets/img/editarIcon.png' alt='icone de editar' style='width: 3em; height: 3em;'></a>
                                    <a onclick='confirmar({$id})'><img src='./assets/img/excluirIcon.png' alt='icone de excluir' style='width: 2.6em; height: 2.6em;'></a>
                                    <a href='/salvar?id={$id}' class='btn btn-outline-primary'>Salvar</a>
                                </td> 
                            </tr>";
                        }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade show" id="editModal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Atualizar informações do aluno:</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="fechar()"></button>
                </div>
                <form action="editar" method="POST">
                    <div class="modal-body">
                        <input type="hidden" name="id" value="<?php echo isset($dados[1]["idalunos"]); ?>">
                        <label for="nome">Editar nome: </label>
                        <input class="form-control bg-light mb-2" name="valor_nome" id="nome" type="text" value="<?php echo isset($dados[1]["nome"]) ? $dados[1]["nome"] : "";?>">
                        <label for="matricula">Editar matricula: </label>
                        <input class="form-control bg-light mb-2" name="valor_matricula" id="matricula" type="text" value="<?php echo isset($dados[1]["matricula"]) ? $dados[1]["matricula"] : "";?>">
                        <label for="cidade">Editar cidade: </label>
                        <input class="form-control bg-light" name="valor_cidade" id="cidade" type="text" value="<?php echo isset($dados[1]["cidade"]) ? $dados[1]["cidade"] : "";?>">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="fechar()">Cancelar</button>
                        <button name="submeter" class="btn btn-primary">Salvar alterações</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function confirmar(id){
            if(confirm('Tem certeza?')){
                location.href = `/excluir?id=${id}`
            }
        }
    </script>
</body>