<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<nav class="container-fluid d-flex justify-content-between w-100 pt-2 pb-2 bg-dark">
    <div class="d-flex gap-2">
        <a class="btn btn-outline-light" href="/"><i>Inicio</i></a>
        <a class="btn btn-outline-light" href="/listar"><i>Listar</i></a>
        <a class="btn btn-outline-light" href="/novo"><i>Novo</i></a>
    </div>
    <div class="text-white fw-bold fs-2">
        <span>CRUD - PHP</span>
    </div>
</nav>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>