<nav class="container-fluid vw-100 d-flex justify-content-between pt-2 pb-2 bg-dark">
    <div class="d-flex gap-2">
        <a class="btn btn-outline-light" href="/"><i>Inicio</i></a>
        <a class="btn btn-outline-light" href="/listar"><i>Listar</i></a>
        <a class="btn btn-outline-light" href="/novo"><i>Novo</i></a>
    </div>
    <div class="text-white fw-bold fs-2">
        <span>CRUD - PHP</span>
    </div>
</nav>